### ISSUE TITLE
Won't translate Ao3 Epubs

### ISSUE THREAD

**Issue by Yinan3** [quantrancse/epub-translator#10]
Hi sorry to bother you, but i found that while trying to translate a few Spanish epubs from https://archiveofourown.org/ that it wasn't translating them to english despite claiming that it did. any suggestions or possible fixes for this? Thank you for your time.

**Comment by quantrancse** [comment]
Hi, can you give me the specific one, so I can test it myself?

**Comment by Yinan3** [comment]
I tried it again just now, just in case, it now works, my best guess is that google was doing something on their end. Again sorry to bother you.
