### ISSUE TITLE
google_new_transError: 404 (Not Found) from TTS API. Probable cause: Unknown

### ISSUE THREAD

**Issue by laraconda** [quantrancse/epub-translator#2]
I'm trying to translate an epub into spanish using the following command:

`python epub-translator.py -l es`

But the following error is thrown:
_google_trans_new.google_trans_new.google_new_transError: 404 (Not Found) from TTS API. Probable cause: Unknown_

I'm using python 3.9 on a conda environment. The requirements listed have been installed.

**Comment by quantrancse** [comment]
It's a bug from google_trans_new [#57](https://github.com/lushan88a/google_trans_new/issues/57). I've fixed it in v1.0.1. Sorry for the late response.
