### ISSUE TITLE
Bug - Just getting jpg from translated version

### ISSUE THREAD

**Issue by Raichard** [quantrancse/epub-translator#3]
Good evening, I want to thank you for this great contribution.
I am using the most recent version to date (1.0.1)
It does not bring me text, only images, the resulting file weighs almost the same as the original file.
Thanks in advance, good luck on the day :3

![imagen](https://user-images.githubusercontent.com/70110092/199645411-050550c7-eb5c-4beb-8a53-5e15fd021978.png)
![imagen](https://user-images.githubusercontent.com/70110092/199645461-ef5147de-4ec3-4fc4-b37e-2a44751dc043.png)
![imagen](https://user-images.githubusercontent.com/70110092/199645529-20401dd0-ff51-44b9-8d2e-85a7f339cd32.png)

**Comment by quantrancse** [comment]
Hi [Raichard] (https://github.com/Raichard), I've tested the ebook above with [v1.0.1](https://github.com/quantrancse/epub-translator/releases/tag/v1.0.1) and still get the text and images. Could you please check again or try to change the e-book reader?

**Comment by Raichard** [comment]
> Hi [Raichard](https://github.com/Raichard), I've tested the ebook above with [v1.0.1](https://github.com/quantrancse/epub-translator/releases/tag/v1.0.1) and still get the text and images. Could you please check again or try to change the e-book reader?

You were right about the viewer, it never crossed my mind that [SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf) would have bugs like that; I'll report it later.
Thank you very much, I love the work you do :3

**Comment by d5364t54ytfr4** [comment]
> Hi [Raichard](https://github.com/Raichard), I've tested the ebook above with [v1.0.1](https://github.com/quantrancse/epub-translator/releases/tag/v1.0.1) and still get the text and images. Could you please check again or try to change the e-book reader?

Same is happening to me. The generated ePub seems to be corrupted in some way and not all ePub Readers are able to deal with it. Some smart  ePub readers like Calibre are able to deal with errors, but in this case Sumatra seems to be incapable.

Edit: Android Readers like @Voice and Evie say that the ePub is damaged.

Solution: Converting the generated ePub to Mobi and then reconverting it back to ePub solves the problem for me.

Also this bug https://github.com/quantrancse/epub-translator/issues/8 where the TOC isn't being translated may be related to this bug.
