### ISSUE TITLE
Fail with no specific error.

### ISSUE THREAD

**Issue by tikityler** [quantrancse/epub-translator#6]
While attempting to translate an Epub from Italian to English it starts to translate, makes it to between 1 and 2% then Fails twice and makes a translated file. 
![translator fail](https://user-images.githubusercontent.com/15217704/205157703-79f016d5-00c6-4438-9772-0be22893add1.png)

**Comment by quantrancse** [comment]
Hi @tikityler, please tell me the name of the book or the epub file so I can figure it out.

**Comment by tikityler** [comment]
Hi @quantrancse  Here is the exact source https://www.amazon.com/gioco-della-pizza-magnifiche-ricette-ebook/dp/B009NEOOFQ

**Comment by tikityler** [comment]
@quantrancse I can provide you with a copy of the epub if that would help. https://drive.google.com/drive/folders/1b9-pOUMuCaBazERBfzWine1q8VW_Ytn_?usp=sharing if you make the request for sharing here I'll give you access.

**Comment by g3ck00** [comment]
Same...

**Comment by g3ck00** [comment]
Same... what to do now...
